apiVersion : v1
kind : Service 
metadata:
  name: k8s-argocd-service
spec:
  type: NodePort
  selector:
    app: k8s-argocd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080